name: Generate AI Packs

on:
  push:
    branches: ['*']

jobs:
  generate-packs:
    runs-on: ubuntu-latest
    
    # Skip if commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor pandoc
          
      - name: Generate AI packs
        run: |
          chmod +x scripts/generate-ai-packs.sh
          ./scripts/generate-ai-packs.sh
          
      - name: Check for changes
        id: check
        run: |
          git add ai/
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto-generate AI packs [skip ci]"
          git push

